# Generated by Django 3.0.3 on 2020-07-01 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classfication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aritcle_type', models.CharField(max_length=128, unique=True, verbose_name='文章类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='标签名')),
                ('c_day', models.DateField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='标题')),
                ('text', models.TextField(blank=True, null=True, verbose_name='文章内容')),
                ('comments', models.TextField(verbose_name='评论')),
                ('likes', models.IntegerField(verbose_name='点赞数')),
                ('notlikes', models.IntegerField(verbose_name='反对数')),
                ('reads', models.IntegerField(verbose_name='阅读量')),
                ('collections', models.IntegerField(verbose_name='收藏量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Classfication', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, to='articles.Tag', verbose_name='标签')),
            ],
        ),
    ]
