# Generated by Django 3.0.3 on 2020-07-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aritcle_type', models.CharField(default='其它', max_length=128, unique=True, verbose_name='文章类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Classification', verbose_name='分类'),
        ),
        migrations.DeleteModel(
            name='Classfication',
        ),
    ]
