# Generated by Django 3.0.3 on 2020-07-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200713_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='collections',
            field=models.IntegerField(default=0, verbose_name='收藏量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='notlikes',
            field=models.IntegerField(default=0, verbose_name='反对数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reads',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
    ]
